################################################################################
#  Tuna analysis
################################################################################
#
# Lina Araón
# linamaragonb@gmail.com
# September 28, 2025
#
# Description
#
################################################################################  


# 1. Load packages ----
# install.packages("janitor")
pkgs <- c("tidyverse", "EVR628tools", "janitor")
lapply(pkgs, library, character.only = T)
remove(pkgs)

# 2. Load data ----
data_catch <- read_csv("data/raw/CatchByFlagGear/CatchByFlagGear1918-2023.csv")
head(data_catch)

# 3. Rename columns ----
data_catch_clean <-data_catch |> 
  janitor::clean_names() |> 
  rename(
    year = ano_year,
    flag = bandera_flag,
    gear = arte_gear,
    species = especies_species,
    catch = t
  )

data_catch_clean


# 4. Filtering data ----

## What are the unique species represented in the data? ----

unique(data_catch_clean$species)

daHow many unique species are there?ta_catch_clean$species |> 
  unique()

## What are the fishing gears represented in the data? ----

unique(data_catch_clean$gear)

data_catch_clean$gear |> 
  unique()

## Does the documentation say what these codes are? ----

Yes

## What is the species code for bigeye tuna? ----

Bigeye tuna = BET

## What is the gear code for purse seine? ----

Purse seine = PS

## Create a new object called ps_tuna_data that takes the tuna_data and filters it to retain data for: bigeye tuna, caught by tuna purse seiners since 2000 ---- 

ps_tuna_data <- data_catch_clean |> 
  filter(
    species == "BET" & gear == "PS" & year >= 2000
  )

ps_tuna_data <- data_catch_clean |> 
  filter(
    species == "BET",
    gear == "PS",
    year >= 2000
  )

ps_tuna_data

range(ps_tuna_data$year)

# 5. Create columns with mutate() ----

#Modify the ps_tuna_data pipeline to create a new column called revenue that calculates the revenue generated by selling the catch
#Make sure you calculate revenues in Millions of USD

ps_tuna_data_rev <- ps_tuna_data |> 
  mutate(
    revenue = ((catch * 1000) * 2),
    revenue_mill = ((catch * 1000) * 2)/1000000
  )

ps_tuna_data_rev
# 6. Calculate group summaries ----

#The data right now report catch at the year-by-flag level. 
#Modify the ps_tuna_data pipeline so that we have total catch and revenue by year

ps_tuna_data_sum <- ps_tuna_data_rev |> 
  group_by(year) |> 
  summarise(across(catch:revenue_mill, sum, .names = "total_{.col}"))

ps_tuna_data_sum 

# 7. Visualize ----

## What is the total revenue? ----

sum(ps_tuna_data_sum$total_revenue_mill)

# ggplot(ps_tuna_data_sum, aes(x = year, y = total_revenue_mill)) +
#   geom_point(size = 3) +
#   labs(title = " Total revenue per year", x = "Year", y = "Total revenue (Million US)")

## What is the average annual revenue? ----

mean(ps_tuna_data_sum$total_revenue_mill)

# ps_tuna_data_mean <- ps_tuna_data_rev |> 
#   group_by(year) |> 
#   summarise(across(catch:revenue_mill, mean, .names = "mean_{.col}"))
# 
# 
# ggplot(ps_tuna_data_mean, aes(x = year, y = mean_revenue_mill)) +
#   geom_point(size = 3) +
#   labs(title = "Mean revenue per year", x = "Year", y = "Mean revenue (Million US)")



## Build a time-series showing revenues by year. ----

ggplot(ps_tuna_data_rev, aes(x = year, y = revenue_mill, col = flag)) +
  geom_point(size = 3) +
  labs(title = "Revenue per year per flag", x = "Year", y = "Revenue (Million US)")

ggplot(ps_tuna_data_sum, aes(x = year, y = total_revenue_mill)) +
  geom_point(size = 3) +
  labs(title = "Total Revenue per year", x = "Year", y = "Revenue (Million US)")

ggplot(ps_tuna_data_rev, aes(x = factor(year), y = revenue_mill)) +
  geom_col(position = "stack") +
  labs(title = "Total Revenue per year", x = "Year", y = "Revenue (Million US)")


